services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    restart: unless-stopped
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/collector-config.yaml
    command: ["--config=/etc/otel/collector-config.yaml"]
    ports:
      - "4317:4317"   # OTLP gRPC
    networks:
      - software_architecture_global-network

networks:
  software_architecture_global-network:
    external: true
