
services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-client=0.0.0.0"]
    networks:
      - global-network
  
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"     
      - "15672:15672"  
    networks:
      - global-network
  

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example123
    networks:
        - global-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  mongo-express: 
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb          # tên container mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example123
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin     # ← QUAN TRỌNG NHẤT: chỉ định database auth là admin
      ME_CONFIG_BASICAUTH_USERNAME: admin        # ← (tùy chọn) login mongo-express bằng user/pass này
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy 
    networks:
      - global-network


   # Health Check-//////////////////////////////////// 
  health-check:
    image: health-check
    container_name: health_check
    build:
      context: .
      dockerfile: ./Services/HealthCheck/HealthCheck.Application/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9000
    ports:
      - "9000:9000"
    depends_on:
        - consul
        - rabbitmq
    networks: 
        - global-network
  
    

  # Gateway-////////////////////////////////////
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./Gateways/Gateways.Ocelot/Dockerfile
    image: api-gateway
    ports:
      - "7000:7000"
    environment:
      - ASPNETCORE_URLS=http://+:7000
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
      
    depends_on:
      - consul
      - orders-api
      - auth.api
      - payment.api
      - voucher.command.api
      - voucher.query.api
    networks:
      - global-network


  


  # Order Service-//////////////////////////////////

  orders.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: orders_db
    hostname: orders-api
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123*
    ports:
      - "1433:1433"
    networks:
      - global-network

  orders-api:
    container_name: orders-api
    build:
      context: .
      dockerfile: ./Services/Orders/Orders.API/Dockerfile

    image: orders-api
    environment:
      # ====== Kết nối database ======
      - ConnectionStrings__Database=Server=orders.db,1433;Database=OrderDb;User Id=sa;Password=Admin123*;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:7003

      # ====== Cấu hình Consul ======
      - ConsulConfig__Address=http://consul:8500
      - ServiceConfig__serviceAddress=http://orders-api:7003
      - ConsulConfig__ServiceName=orders-api
      - ConsulConfig__ServicePort=7003

    depends_on:
      - orders.db
      - consul
      - rabbitmq
    ports:
      - "7003:7003"
    networks:
      - global-network

    # Order Orchestration-////////////////////////////////////
  order.orchestration:
     container_name: order-orchestration
     build:
        context: .
        dockerfile: ./Services/Orders/Orders.Orchestrator/Dockerfile
     image: order-orchestration
     environment:
        - ASPNETCORE_URLS=http://+:7033
        - ASPNETCORE_ENVIRONMENT=Development
        - SagaSettings__MongoDbConnection=mongodb://root:example123@mongodb:27017
        - SagaSettings__DatabaseName=food_delivery_saga
     depends_on:
        mongodb:
            condition: service_healthy  
        rabbitmq:
            condition: service_started
        consul:
            condition: service_started
     ports:
        - "7033:7033"
     networks:
        - global-network

  # Auth Service-///////////////////////////////////
  auth.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: auth_db
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Admin123*
    ports:
    - "1436:1433"
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Admin123*" -Q "SELECT 1"
        interval: 10s
        timeout: 5s
        retries: 10
    networks:
        - global-network


  auth.api:
    container_name: auth-api
    build:
        context: .
        dockerfile: ./Services/Auth/Auth.API/Dockerfile
    image: auth-api
    environment:
        - ConnectionStrings__Database=Server=auth.db,1433;Database=AuthDb;User Id=sa;Password=Admin123*;TrustServerCertificate=True;
        - ASPNETCORE_URLS=http://+:7001
        - ASPNETCORE_ENVIRONMENT=Development
        - ConsulConfig__Address=http://consul:8500
        - ConsulConfig__ServiceName=auth-api
        - ConsulConfig__ServicePort=7001
    depends_on:
        auth.db:
            condition: service_healthy
        consul:
            condition: service_healthy
    ports:
        - "7001:7001"
    networks:
        - global-network

   
  # Voucher Service-///////////////////////////////////

  voucher.write.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: voucher_write_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123*
    ports:
      - "1434:1433"
    networks:
      - global-network


  voucher.command.api:
    container_name: voucher-command-api
    build:
        context: .
        dockerfile: ./Services/VoucherAPI/Voucher.CommandAPI/Dockerfile
    image: voucher-command-api
    environment:
        - ConnectionStrings__Database=Server=voucher.write.db,1433;Database=VoucherWriteDB;User Id=sa;Password=Admin123*;TrustServerCertificate=True;
        - ASPNETCORE_URLS=http://+:7004
        - ASPNETCORE_ENVIRONMENT=Development
        - ConsulConfig__Address=http://consul:8500
        - ConsulConfig__ServiceName=voucher-command-api
        - ConsulConfig__ServicePort=7004
    depends_on:
        - voucher.write.db
        - consul
        - rabbitmq
    ports:
        - "7004:7004"
    networks:
        - global-network
  

  voucher.read.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: voucher_read_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123*
    ports:
      - "1435:1433"
    networks:
      - global-network
  
  voucher.query.api:
    container_name: voucher-query-api
    build:
        context: .
        dockerfile: ./Services/VoucherAPI/Voucher.QueryAPI/Dockerfile
    image: voucher-query-api
    environment:
        - ConnectionStrings__Database=Server=voucher.read.db,1433;Database=VoucherReadDB;User Id=sa;Password=Admin123*;TrustServerCertificate=True;
        - ASPNETCORE_URLS=http://+:7006
        - ASPNETCORE_ENVIRONMENT=Development
        - ConsulConfig__Address=http://consul:8500
        - ConsulConfig__ServiceName=voucher-query-api
        - ConsulConfig__ServicePort=7006
    depends_on:
        - voucher.read.db
        - consul
        - rabbitmq
    ports:
        - "7006:7006"
    networks:
        - global-network


   # Payment Service-///////////////////////////////////
  payment.api:
    container_name: payment-api
    build:
        context: .
        dockerfile: ./Services/Payment/Payment.API/Dockerfile

    image: payment-api
    environment:
        - ASPNETCORE_URLS=http://+:7005
        - ConsulConfig__Address=http://consul:8500
        - ConsulConfig__ServiceName=payment-api
        - ConsulConfig__ServicePort=7005
    depends_on:
        - consul
        - rabbitmq
    ports:
        - "7005:7005"
    networks:
        - global-network

volumes:
  mongo-data:

networks:
  auth-network:
    driver: bridge
  voucher-network:
    driver: bridge
  order-network:
    driver: bridge
  global-network:
    driver: bridge
