<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bb156916-1fbc-4b9a-a8fa-6ee35514368a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consul" Version="1.7.14.9" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    

	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Integrations\Integrations.Consul\Integrations.Consul.csproj" />
    <ProjectReference Include="..\..\..\Integrations\Integrations.OpenTelemetry\Integrations.OpenTelemetry.csproj" />
    <ProjectReference Include="..\Payment.Messaging\Payment.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
