version: '3.9'

services:
  orders.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: orders_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123*
    ports:
      - "1433:1433"
    networks:
      - orders-network

  orders.api:
    container_name: orders_api
    build:
      context: ../..   # <-- từ Services/Orders đến root
      dockerfile: Services/Orders/Orders.API/Dockerfile
    environment:
      - ConnectionStrings__Database=Server=orders.db,1433;Database=OrderDb;User Id=sa;Password=Admin123*;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:7003
      - CONSUL_HOST=consul
    depends_on:
      - orders.db
    ports:
      - "7003:7003"
    networks:
      - orders-network
      - global-network

networks:
  orders-network:
    driver: bridge
  global-network:
    external: true
