<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bafe83eb-33ce-4bc0-b47b-755386f85c6d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <!-- HealthChecks version dành cho .NET 8 -->
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />

    <!-- Carter đúng version .NET 8 -->
    <PackageReference Include="Carter" Version="8.0.0" />

    <!-- MassTransit 8.5.5 : phiên bản ổn định nhất trong .NET 8 -->
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />

    <!-- MediatR mới nhất, tương thích .NET 8 -->
    <PackageReference Include="MediatR" Version="12.2.0" />

    <!-- Diagnostics của .NET 8 -->
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.0" />

    <!-- EF Core Design 8.x để chạy migrations -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Integrations\Integrations.Consul\Integrations.Consul.csproj" />
    <ProjectReference Include="..\Voucher.Application\Voucher.Application.csproj" />
    <ProjectReference Include="..\Voucher.Infrastructure\Voucher.Infrastructure.csproj" />
    <ProjectReference Include="..\Voucher.Shared\Voucher.Shared.csproj" />
  </ItemGroup>

</Project>
